version: '3.7'

services:

    front-end:
        build:
            context: .
            target: app
            args:
                - PORT=3000
                - NODE_ENV=development
        volumes:
            - ".:/twitter-dashboard"
        ports:
            - "8080:3000"
        stdin_open: true

    cli:
        build:
            context: .
            target: cli
        volumes:
            - ".:/twitter-dashboard" 
    