version: '3.7'

services:

    front-end:
        build:
            context: .
            target: dev-app
            args:
                - PORT=8080
                - NODE_ENV=development
        volumes:
            - ".:/twitter-dashboard"
        ports:
            - "8080:8080"
        stdin_open: true

    cli:
        build:
            context: .
            target: cli
        volumes:
            - ".:/twitter-dashboard" 
    